#!/usr/bin/env python3

# This file is part of dh-cmake.
# See top-level LICENSE file for license information.

import dh_cmake_common

import os.path
import re


dh_cmake_common.init()

topdir = os.getcwd()
os.chdir(os.path.join(topdir, "debian", "build"))
for filename in os.listdir(os.path.join(topdir, "debian")):
    match = re.search("^(.*)\\.cpack-components", filename)
    if match:
        package_name = match.group(1)
        with open(os.path.join(topdir, "debian", filename), "r") as f:
            for line in f:
                component_name = line.rstrip()
                os.environ["DESTDIR"] = os.path.join(topdir, "debian", package_name)
                dh_cmake_common.do_cmd(["cmake", "-DCMAKE_INSTALL_COMPONENT=" + component_name, "-P", "cmake_install.cmake"])
